# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: example.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import other_pb2 as other__pb2


DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\rexample.proto\x12\x07\x65xample\x1a\x0bother.proto\"\xa8\x01\n\x06Person\x12\x0c\n\x04name\x18\x01 \x01(\t\x12\n\n\x02id\x18\x02 \x01(\x05\x12\x0e\n\x06\x65mails\x18\x03 \x03(\t\x12\'\n\x04\x64ict\x18\x04 \x03(\x0b\x32\x19.example.Person.DictEntry\x12\x1e\n\x06orders\x18\x05 \x03(\x0b\x32\x0e.example.Order\x1a+\n\tDictEntry\x12\x0b\n\x03key\x18\x01 \x01(\t\x12\r\n\x05value\x18\x02 \x01(\x05:\x02\x38\x01\"y\n\x0eSearchResponse\x12/\n\x07results\x18\x01 \x03(\x0b\x32\x1e.example.SearchResponse.Result\x1a\x36\n\x06Result\x12\x0b\n\x03url\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x10\n\x08snippets\x18\x03 \x03(\tB\nZ\x08./;eventb\x06proto3')



_PERSON = DESCRIPTOR.message_types_by_name['Person']
_PERSON_DICTENTRY = _PERSON.nested_types_by_name['DictEntry']
_SEARCHRESPONSE = DESCRIPTOR.message_types_by_name['SearchResponse']
_SEARCHRESPONSE_RESULT = _SEARCHRESPONSE.nested_types_by_name['Result']
Person = _reflection.GeneratedProtocolMessageType('Person', (_message.Message,), {

  'DictEntry' : _reflection.GeneratedProtocolMessageType('DictEntry', (_message.Message,), {
    'DESCRIPTOR' : _PERSON_DICTENTRY,
    '__module__' : 'example_pb2'
    # @@protoc_insertion_point(class_scope:example.Person.DictEntry)
    })
  ,
  'DESCRIPTOR' : _PERSON,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:example.Person)
  })
_sym_db.RegisterMessage(Person)
_sym_db.RegisterMessage(Person.DictEntry)

SearchResponse = _reflection.GeneratedProtocolMessageType('SearchResponse', (_message.Message,), {

  'Result' : _reflection.GeneratedProtocolMessageType('Result', (_message.Message,), {
    'DESCRIPTOR' : _SEARCHRESPONSE_RESULT,
    '__module__' : 'example_pb2'
    # @@protoc_insertion_point(class_scope:example.SearchResponse.Result)
    })
  ,
  'DESCRIPTOR' : _SEARCHRESPONSE,
  '__module__' : 'example_pb2'
  # @@protoc_insertion_point(class_scope:example.SearchResponse)
  })
_sym_db.RegisterMessage(SearchResponse)
_sym_db.RegisterMessage(SearchResponse.Result)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010./;event'
  _PERSON_DICTENTRY._options = None
  _PERSON_DICTENTRY._serialized_options = b'8\001'
  _PERSON._serialized_start=40
  _PERSON._serialized_end=208
  _PERSON_DICTENTRY._serialized_start=165
  _PERSON_DICTENTRY._serialized_end=208
  _SEARCHRESPONSE._serialized_start=210
  _SEARCHRESPONSE._serialized_end=331
  _SEARCHRESPONSE_RESULT._serialized_start=277
  _SEARCHRESPONSE_RESULT._serialized_end=331
# @@protoc_insertion_point(module_scope)
