# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: other.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0bother.proto\x12\x07\x65xample\"a\n\x05Order\x12\n\n\x02id\x18\x01 \x01(\x03\x12\x0c\n\x04\x64\x61te\x18\x02 \x01(\x04\x12\x10\n\x08\x63ustomer\x18\x03 \x01(\t\x12\r\n\x05price\x18\x04 \x01(\x01\x12\r\n\x05goods\x18\x05 \x01(\t\x12\x0e\n\x06remark\x18\x06 \x01(\tB\nZ\x08./;eventb\x06proto3')



_ORDER = DESCRIPTOR.message_types_by_name['Order']
Order = _reflection.GeneratedProtocolMessageType('Order', (_message.Message,), {
  'DESCRIPTOR' : _ORDER,
  '__module__' : 'other_pb2'
  # @@protoc_insertion_point(class_scope:example.Order)
  })
_sym_db.RegisterMessage(Order)

if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  DESCRIPTOR._serialized_options = b'Z\010./;event'
  _ORDER._serialized_start=24
  _ORDER._serialized_end=121
# @@protoc_insertion_point(module_scope)
